// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopListBackend.Data;

#nullable disable

namespace shoplistbackend.Migrations
{
    [DbContext(typeof(ShopListDbContext))]
    partial class ShopListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopListBackend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "חלב וגבינות"
                        },
                        new
                        {
                            Id = 2,
                            Name = "טואלטיקה"
                        },
                        new
                        {
                            Id = 3,
                            Name = "בשר"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ירקות ופירות"
                        });
                });

            modelBuilder.Entity("ShopListBackend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "קוטג"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "חלב 3%"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "שמנת חמוצה"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "יוגורט"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "סבון"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "שמפו"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "נייר טואלט"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "בקר"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "עוף"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "הודו"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Name = "כבש"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "גזר"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Name = "מנגו"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Name = "אבטיח"
                        });
                });

            modelBuilder.Entity("ShopListBackend.Models.Product", b =>
                {
                    b.HasOne("ShopListBackend.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShopListBackend.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
